language: ganeric
sudo: required
services:
    - docker 
before_install:
    - docker build -t danarus/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true danarus/react-test npm test
after_success:
    - docker build -t danarus/multi_client ./client 
    - docker build -t danarus/multi_nginx ./nginx 
    - docker build -t danarus/multi_server ./server
    - docker build -t danarus/multi_worker ./worker
#Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --paasword-stdin
#Take those images and deploy 
    - docker push danarus/multi_client
    - docker push danarus/multi_nginx 
    - docker push danarus/multi_server
    - docker push danarus/multi_worke