version: "3"
services: 
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
    nginx:
        depends_on: 
            - client
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - 3050:80