version: "3"
services: 
    api: 
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
    nginx:
        depends_on: 
            - api
            - client
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - 3050:80